#!/usr/bin/env python3
"""
Generate test cases for chapters 03, 05, 07, 11 which are missing TC definitions.
Based on bug annotations (🔴/🟡) and flow diagrams in those chapters.
"""

# Ch03: Service Lifecycle — based on startup/shutdown/power/session flows
CH03_TCS = [
    {
        "id": "TC-03-01", "name": "Service Startup Sequence — Module Init Order",
        "feature": "Service Lifecycle",
        "platform": "Windows",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Test Gap",
        "related_bugs": "",
        "preconditions": "Windows machine with NSClient installed; service stopped",
        "steps": "1. Start stAgentSvc service | 2. Monitor nsdebuglog.log for module init sequence | 3. Verify OnInit → onLogon → onConfigReady order | 4. Verify all member objects initialized (TunnelMgr, ConfigMgr, NSCom2Server, etc.) | 5. Verify tunnel connects after config ready | 6. Verify UI receives status update via IPC",
        "expected_result": "Service starts cleanly in correct sequence; all modules initialize without error; tunnel establishes within 30s of config ready",
        "failure_indicators": "grep -i \"init.*fail\\|module.*error\\|startup.*timeout\\|OnInit.*exception\" nsdebuglog.log",
        "risk": "Incorrect startup order causes module dependency failures; tunnel never establishes",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-03-02", "name": "Graceful Shutdown — Module Teardown Order",
        "feature": "Service Lifecycle",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P1", "gap_type": "Test Gap",
        "related_bugs": "ENG-733657",
        "preconditions": "Windows machine with NSClient running; tunnel connected; FailClose enabled",
        "steps": "1. Stop stAgentSvc via sc stop | 2. Monitor shutdown sequence in logs | 3. Verify FilterDevice rules cleared before service stops | 4. Verify tunnel gracefully disconnects | 5. Verify IPC notifies UI | 6. Verify no orphaned processes",
        "expected_result": "Service stops gracefully; FilterDevice rules cleared (no residual FailClose); all modules tear down in reverse order",
        "failure_indicators": "grep -i \"shutdown.*timeout\\|driver.*rules.*residual\\|orphan\\|hang\" nsdebuglog.log",
        "risk": "Residual FilterDevice rules cause permanent network block after service stop (ENG-733657 pattern)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-03-03", "name": "Service Crash Recovery — Watchdog Restart",
        "feature": "Service Lifecycle",
        "platform": "Windows",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Test Gap",
        "related_bugs": "",
        "preconditions": "Windows machine with NSClient running; Watchdog enabled",
        "steps": "1. Kill stAgentSvc process via taskkill /F | 2. Wait 60 seconds | 3. Verify Watchdog restarts service | 4. Verify tunnel reconnects | 5. Verify no duplicate device IDs | 6. Verify FailClose does not falsely activate during restart window",
        "expected_result": "Service restarted within 60s; tunnel reconnected; no false FailClose activation",
        "failure_indicators": "grep -i \"watchdog.*fail\\|restart.*timeout\\|duplicate.*device\" nsdebuglog.log",
        "risk": "Unrecovered service crash leaves user without security protection",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-03-04", "name": "Power Resume — AOAC Modern Standby Wake",
        "feature": "Service Lifecycle",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P2", "gap_type": "Test Gap",
        "related_bugs": "ENG-726784",
        "preconditions": "Windows 11 device with Modern Standby (AOAC) enabled; tunnel connected",
        "steps": "1. Put device into Modern Standby (close lid) | 2. Wait 30+ minutes | 3. Wake device (open lid) | 4. Verify service is RUNNING (not zombie) | 5. Verify tunnel reconnects or is already connected | 6. Check no duplicate device ID created (ENG-726784)",
        "expected_result": "Service recovers from AOAC wake; tunnel operational; no duplicate device IDs",
        "failure_indicators": "grep -i \"zombie\\|duplicate.*uid\\|standby.*fail\\|power.*resume.*error\" nsdebuglog.log",
        "risk": "AOAC zombie state leaves users unprotected despite service appearing healthy",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-03-05", "name": "Windows Session Change — User Logon/Logoff",
        "feature": "Service Lifecycle",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P2", "gap_type": "Test Gap",
        "related_bugs": "ENG-591721",
        "preconditions": "Windows machine; NSClient running; user logged in with active tunnel",
        "steps": "1. Log off current user | 2. Verify service handles session change event | 3. Log in as different user | 4. Verify onLogon triggers re-initialization | 5. Verify tunnel remains or reconnects for new user | 6. Verify no IPC deadlock (ENG-591721)",
        "expected_result": "Session change handled gracefully; new user gets tunnel protection; no deadlock",
        "failure_indicators": "grep -i \"deadlock\\|session.*change.*error\\|logon.*fail\" nsdebuglog.log",
        "risk": "Session change deadlock blocks all users in VDI environment",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-03-06", "name": "Service Startup with Missing Dependencies",
        "feature": "Service Lifecycle",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P2", "gap_type": "Test Gap",
        "related_bugs": "",
        "preconditions": "Windows machine with NSClient installed",
        "steps": "1. Disable BFE (Base Filtering Engine) service | 2. Start stAgentSvc | 3. Verify graceful error handling (not crash) | 4. Re-enable BFE | 5. Restart stAgentSvc | 6. Verify full recovery without reinstallation",
        "expected_result": "Service reports clear error when dependency missing; recovers once dependency restored",
        "failure_indicators": "grep -i \"BFE\\|dependency.*fail\\|driver.*load.*error\" nsdebuglog.log",
        "risk": "Service crash loop when dependency unavailable; no clear error for troubleshooting",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-03-07", "name": "macOS launchd KeepAlive Recovery",
        "feature": "Service Lifecycle",
        "platform": "macOS",
        "severity": "S2", "auto_priority": "P2", "gap_type": "Test Gap",
        "related_bugs": "",
        "preconditions": "macOS with NSClient installed and running",
        "steps": "1. Kill stAgentSvc daemon (kill -9) | 2. Verify launchd restarts it within 10s | 3. Kill 5 times rapidly | 4. Verify launchd rate-limits restarts | 5. Verify no CPU spike from crash loop | 6. After rate limit, verify eventual recovery",
        "expected_result": "launchd auto-restarts crashed service; rate limiting prevents CPU exhaustion",
        "failure_indicators": "CPU > 80%; service remains dead after 60s; log shows crash loop",
        "risk": "Service crash loop consumes system resources on macOS",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-03-08", "name": "Linux systemd Restart Policy",
        "feature": "Service Lifecycle",
        "platform": "Linux",
        "severity": "S3", "auto_priority": "P3", "gap_type": "Test Gap",
        "related_bugs": "",
        "preconditions": "Linux with NSClient installed via .run/.deb",
        "steps": "1. Kill stagentd (SIGKILL) | 2. Verify restart within 10s (Restart=always) | 3. Kill stagentapp (SIGTERM) | 4. Verify NOT restarted (on-failure only, clean exit) | 5. Kill stagentapp (SIGABRT) | 6. Verify restarted within 5s (failure exit)",
        "expected_result": "systemd respects restart policies: daemon always restarts; app only on failure",
        "failure_indicators": "systemctl status stagentd shows dead; unexpected restart behavior",
        "risk": "Incorrect restart behavior leaves users unprotected",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-03-09", "name": "Network Change Event Handling",
        "feature": "Service Lifecycle",
        "platform": "Cross-Platform",
        "severity": "S2", "auto_priority": "P1", "gap_type": "Day-1",
        "related_bugs": "ENG-393015",
        "preconditions": "Device with NSClient running; tunnel connected; WiFi and Ethernet available",
        "steps": "1. Switch from WiFi to Ethernet | 2. Verify service handles network change event | 3. Verify tunnel reconnects on new interface | 4. Switch back to WiFi | 5. Rapidly switch 5 times | 6. Verify no crash (ENG-393015) and tunnel recovers each time",
        "expected_result": "Service handles all network changes gracefully; tunnel reconnects; no crash",
        "failure_indicators": "grep -i \"crash\\|network.*change.*fail\\|reconnect.*timeout\" nsdebuglog.log",
        "risk": "Network switch causes crash (ENG-393015) or permanent tunnel loss",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-03-10", "name": "VDI Multi-Session Service Lifecycle",
        "feature": "Service Lifecycle",
        "platform": "Windows",
        "severity": "S1", "auto_priority": "P2", "gap_type": "Corner Case",
        "related_bugs": "ENG-591721, ENG-918131",
        "preconditions": "Windows Server RDS/Citrix with 5+ concurrent user sessions",
        "steps": "1. Verify service handles all sessions simultaneously | 2. User A logs off while User B enrolls | 3. Verify no deadlock (ENG-591721) | 4. Verify no 20s delay (ENG-918131) | 5. Kill service and verify all sessions recover after restart | 6. Verify session isolation maintained",
        "expected_result": "All sessions managed independently; no deadlock; recovery affects all sessions equally",
        "failure_indicators": "grep -i \"deadlock\\|20.*second.*delay\\|session.*isolation\\|hang\" nsdebuglog.log",
        "risk": "VDI deadlock affects all concurrent users; mass outage from single service issue",
        "automation": "❌ Not covered",
    },
]

# Ch05: Steering Config — 103 bugs, highest density
CH05_TCS = [
    {
        "id": "TC-05-01", "name": "Steering Mode NONE — No Tunnel Activation",
        "feature": "Steering Config",
        "platform": "Windows",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-384041",
        "preconditions": "Windows device; steering mode set to NONE in admin console; FailClose enabled",
        "steps": "1. Configure steering mode = NONE | 2. Wait for config download | 3. Verify tunnel is NOT established | 4. Verify FailClose does NOT activate (should stay Backed Off) | 5. Verify all traffic passes directly (not through tunnel) | 6. Switch to Web mode and verify tunnel starts",
        "expected_result": "NONE mode does not trigger tunnel or FailClose; all traffic passes directly",
        "failure_indicators": "grep -i \"FailClose.*active\\|tunnel.*connect\\|NONE.*should.*bypass\" nsdebuglog.log",
        "risk": "NONE mode falsely triggers FailClose, blocking all user traffic (ENG-384041)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-02", "name": "Dynamic Steering — On-Prem to Off-Prem Switch",
        "feature": "Steering Config",
        "platform": "Windows",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-455132, ENG-918451",
        "preconditions": "Windows device; Dynamic Steering enabled; on-prem and off-prem profiles configured differently",
        "steps": "1. While on corporate network, verify on-prem steering profile active | 2. Disconnect from corporate (go off-prem) | 3. Verify off-prem profile applied within 30s | 4. Verify on-prem rules do NOT apply off-prem (ENG-455132) | 5. Reconnect to corporate | 6. Verify on-prem profile resumes correctly (ENG-918451)",
        "expected_result": "Steering profile switches correctly with location; no cross-contamination of rules",
        "failure_indicators": "grep -i \"on-prem.*off-prem\\|profile.*switch.*fail\\|wrong.*rule\" nsdebuglog.log",
        "risk": "Off-prem rules applied on-prem (ENG-455132) or on-prem rules stuck (ENG-918451)",
        "automation": "⚠️ Partial — dynamic_steering/test_p0.py covers basic on/off-prem switch",
    },
    {
        "id": "TC-05-03", "name": "Config Update — Steering Mode Change (NONE to Web/All)",
        "feature": "Steering Config",
        "platform": "Windows",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-591725, ENG-422599",
        "preconditions": "Windows device; currently in NONE mode; FailClose enabled",
        "steps": "1. Current mode is NONE (no tunnel) | 2. Admin changes steering to WEB mode | 3. Wait for config download | 4. Verify tunnel starts after mode change | 5. Verify FailClose does NOT falsely activate during transition (ENG-422599) | 6. Verify traffic now steered correctly through tunnel",
        "expected_result": "Mode change triggers tunnel start; no false FailClose during transition",
        "failure_indicators": "grep -i \"NONE.*to.*Web.*fail\\|tunnel.*not.*started\\|FailClose.*config.*update\" nsdebuglog.log",
        "risk": "Tunnel not started after mode change (ENG-591725); false FailClose blocks traffic (ENG-422599)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-04", "name": "Exception List — Wildcard 0.0.0.0/0 Total Bypass",
        "feature": "Steering Config",
        "platform": "Cross-Platform",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-855335",
        "preconditions": "Device with NSClient; admin console access",
        "steps": "1. Configure exception with 0.0.0.0/0 or ::/0 or ::/128 | 2. Download config | 3. Verify if ALL traffic is bypassed | 4. Client should reject or warn about wildcard exceptions | 5. Remove wildcard and verify normal steering resumes | 6. Verify no error in exception parsing",
        "expected_result": "Wildcard exception either rejected or generates admin warning; does not cause total bypass silently",
        "failure_indicators": "grep -i \"Adding.*0.0.0.0.*Exception\\|total.*bypass\\|all.*traffic.*bypassed\" nsdebuglog.log",
        "risk": "Complete security bypass — all traffic avoids Netskope inspection (ENG-855335)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-05", "name": "Domain List — 30K+ Domains Stability",
        "feature": "Steering Config",
        "platform": "Android/ChromeOS",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Corner Case",
        "related_bugs": "ENG-872456",
        "preconditions": "Android/ChromeOS device; admin configures 30K+ domains in steering",
        "steps": "1. Configure 30K+ domains in steering config | 2. Push config to device | 3. Verify client does not crash on config parse | 4. Verify memory usage is bounded | 5. Verify domain lookup performance remains acceptable | 6. Reduce to 10K domains and verify recovery",
        "expected_result": "Client handles large domain list without crash; graceful handling if limit exceeded",
        "failure_indicators": "grep -i \"OOM\\|buffer.*overflow\\|crash\\|domain.*parse.*fail\" nsdebuglog.log",
        "risk": "Client crash on large config (ENG-872456); all users with large configs affected",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-06", "name": "Config Callback — Non-Atomic Update Race Condition",
        "feature": "Steering Config",
        "platform": "Cross-Platform",
        "severity": "S2", "auto_priority": "P1", "gap_type": "Test Gap",
        "related_bugs": "ENG-739968",
        "preconditions": "Device with active traffic; config update pending",
        "steps": "1. Establish active connections through tunnel | 2. Trigger config update that changes exception list | 3. During update, verify no packets misclassified | 4. Verify nsexception.json write-read lock prevents race (ENG-739968) | 5. Verify tunnel does not disconnect during config apply | 6. Verify FailClose not triggered during transition window",
        "expected_result": "Config update atomic; no traffic misclassification during transition",
        "failure_indicators": "grep -i \"race\\|nsexception.*corrupt\\|misclassif\\|write.*read.*lock\" nsdebuglog.log",
        "risk": "Traffic incorrectly steered/bypassed during config transition (ENG-739968)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-07", "name": "DNS over TCP Learning in WFP Driver",
        "feature": "Steering Config",
        "platform": "Windows",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Day-1",
        "related_bugs": "ENG-438566, ENG-456732",
        "preconditions": "Windows device; DNS resolver uses TCP for large responses",
        "steps": "1. Configure steering for DNS traffic | 2. Generate DNS query that returns TCP response (large DNS) | 3. Verify WFP driver learns DNS over TCP correctly | 4. Verify no BSOD from fix regression (ENG-456732) | 5. Verify DNS traffic steered correctly | 6. Verify non-DNS TCP traffic not affected",
        "expected_result": "DNS over TCP correctly intercepted; no BSOD; non-DNS TCP unaffected",
        "failure_indicators": "BSOD; grep -i \"DNS.*TCP.*learn\\|BSOD\\|bugcheck\" nsdebuglog.log",
        "risk": "BSOD from DNS TCP fix regression (ENG-456732); DNS not steered (ENG-438566)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-08", "name": "Category Bypass — IP vs Hostname Access",
        "feature": "Steering Config",
        "platform": "Cross-Platform",
        "severity": "S2", "auto_priority": "P2", "gap_type": "Day-1",
        "related_bugs": "ENG-395253",
        "preconditions": "Category bypass configured for a specific category (e.g., Financial Services)",
        "steps": "1. Access website by hostname — verify bypassed after category probe | 2. Access same website by IP address — verify NOT bypassed | 3. Verify no category probe for IP access | 4. Verify logs explain IP access behavior | 5. Access different category by hostname — verify NOT bypassed | 6. Toggle category bypass off and verify traffic steered",
        "expected_result": "Category bypass works by hostname only; IP access not category-matched (known limitation)",
        "failure_indicators": "grep -i \"category.*bypass\\|probe.*fail\\|IP.*access.*bypass\" nsdebuglog.log",
        "risk": "Unexpected category bypass behavior confuses admins (ENG-395253)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-09", "name": "Custom Port Steering — UDP 3478 in Web Mode",
        "feature": "Steering Config",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P1", "gap_type": "Day-1",
        "related_bugs": "ENG-448002",
        "preconditions": "Windows device; steering mode = WEB; custom port exceptions configured",
        "steps": "1. Set steering mode to WEB | 2. Generate UDP port 3478 traffic (STUN/TURN for Teams) | 3. Verify UDP 3478 is NOT steered in Web mode (should bypass) | 4. Switch to ALL mode | 5. Verify UDP 3478 IS steered in ALL mode | 6. Verify custom port exception works correctly",
        "expected_result": "Web mode only steers HTTP/HTTPS; non-web ports like UDP 3478 correctly bypassed",
        "failure_indicators": "grep -i \"UDP.*3478.*steer\\|port.*incorrect\\|web.*mode.*udp\" nsdebuglog.log",
        "risk": "Non-web traffic incorrectly steered, breaking real-time communications (ENG-448002)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-10", "name": "DNS Traffic Steering After FailClose Recovery",
        "feature": "Steering Config",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-561500",
        "preconditions": "Windows device; FailClose enabled; DNS steering active",
        "steps": "1. Verify DNS traffic steered through tunnel | 2. Disconnect tunnel to trigger FailClose | 3. Wait for FailClose to activate | 4. Reconnect tunnel (FailClose recovery) | 5. Verify DNS traffic is AGAIN steered through tunnel (ENG-561500) | 6. Verify DNS resolution works correctly after recovery",
        "expected_result": "DNS steering fully restored after FailClose recovery; no stale DNS state",
        "failure_indicators": "grep -i \"DNS.*not.*steered\\|DNS.*steer.*recovery\\|DNS.*flush\" nsdebuglog.log",
        "risk": "DNS not steered after FC recovery — security bypass for DNS-based policies (ENG-561500)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-11", "name": "Cert-Pinned App + DNS TCP Block",
        "feature": "Steering Config",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P2", "gap_type": "Day-1",
        "related_bugs": "ENG-718498",
        "preconditions": "Windows device; cert-pinned app configured with block action; DNS Security enabled",
        "steps": "1. Configure cert-pinned app with block action | 2. Enable DNS Security (DNS TCP steering) | 3. Generate DNS over TCP traffic from cert-pinned app | 4. Verify DNS TCP traffic is correctly blocked (not bypassed) | 5. Verify regular DNS UDP from same app is handled correctly | 6. Verify non-cert-pinned DNS TCP is steered normally",
        "expected_result": "DNS TCP from cert-pinned blocked app is correctly blocked; no bypass loophole",
        "failure_indicators": "grep -i \"DNS.*TCP.*bypass\\|cert.*pin.*DNS\\|block.*bypass\" nsdebuglog.log",
        "risk": "DNS TCP bypasses cert-pinned block, allowing blocked apps to resolve domains (ENG-718498)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-12", "name": "User/Group Case-Sensitive ID Assignment",
        "feature": "Steering Config",
        "platform": "Cross-Platform",
        "severity": "S2", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-693785",
        "preconditions": "Device enrolled; user/group-based steering profiles configured",
        "steps": "1. Configure steering profile for user 'User@Corp.com' | 2. Enroll device with UPN 'user@corp.com' (different case) | 3. Verify correct steering profile assigned despite case difference | 4. Change user group name case in admin | 5. Verify assignment not broken by case change | 6. Verify all platforms handle case-insensitive matching",
        "expected_result": "User/group matching is case-insensitive; profile correctly assigned regardless of case",
        "failure_indicators": "grep -i \"user.*mismatch\\|group.*not.*found\\|case.*sensitive\" nsdebuglog.log",
        "risk": "Wrong steering profile applied due to case mismatch (ENG-693785)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-13", "name": "DHCP Traffic in CFW Mode on macOS 15.x",
        "feature": "Steering Config",
        "platform": "macOS",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Corner Case",
        "related_bugs": "ENG-655009",
        "preconditions": "macOS 15.x; CFW (Cloud Firewall) steering mode enabled",
        "steps": "1. Enable CFW mode in steering config | 2. Connect to new WiFi network (triggers DHCP) | 3. Verify DHCP request/response not intercepted by NE | 4. Verify device gets IP address correctly | 5. Verify subsequent traffic steered through tunnel | 6. Switch networks and verify DHCP works again",
        "expected_result": "DHCP traffic bypassed correctly in CFW mode; device always gets IP",
        "failure_indicators": "grep -i \"DHCP.*fail\\|no.*IP\\|CFW.*DHCP\" nsdebuglog.log; no network connectivity",
        "risk": "DHCP intercepted in CFW mode — device can't get IP address on new networks",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-14", "name": "VDI Session-Specific Steering Profile",
        "feature": "Steering Config",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P2", "gap_type": "Corner Case",
        "related_bugs": "ENG-624953, ENG-710784",
        "preconditions": "Citrix VDI; 3+ users with different steering profiles",
        "steps": "1. User A logged in with Web mode profile | 2. User B logged in with ALL mode profile | 3. User C logged in with custom exceptions | 4. Verify each user's traffic steered per their profile | 5. User A logs off — verify B and C unaffected | 6. Verify no cross-session steering contamination",
        "expected_result": "Each VDI session applies correct steering profile independently",
        "failure_indicators": "grep -i \"session.*steer\\|cross.*contamination\\|wrong.*profile\" nsdebuglog.log",
        "risk": "Wrong steering profile applied in VDI; one user's security policy leaks to another",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-05-15", "name": "IPv6 Blocking and Link-Local DNS Handling",
        "feature": "Steering Config",
        "platform": "Cross-Platform",
        "severity": "S2", "auto_priority": "P1", "gap_type": "Test Gap",
        "related_bugs": "",
        "preconditions": "Device with IPv6 enabled; link-local IPv6 DNS configured",
        "steps": "1. Enable IPv6 on device | 2. Verify IPv6 traffic handling per steering mode | 3. Test link-local DNS (fe80::) resolution | 4. Verify IPv6 CIDR exceptions work correctly | 5. Test compressed vs expanded IPv6 format matching | 6. Verify no traffic leak through IPv6 when IPv4 steered",
        "expected_result": "IPv6 handled consistently; link-local DNS works; no IPv6 traffic leaks",
        "failure_indicators": "grep -i \"IPv6.*leak\\|link.*local.*fail\\|CIDR.*mismatch\" nsdebuglog.log",
        "risk": "IPv6 traffic bypasses steering silently; security gap for dual-stack environments",
        "automation": "❌ Not covered",
    },
]

# Ch07: Tunnel Management — 59 bugs
CH07_TCS = [
    {
        "id": "TC-07-01", "name": "DTLS to TLS Fallback on Handshake Failure",
        "feature": "Tunnel Management",
        "platform": "Cross-Platform",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-503501",
        "preconditions": "Device with NSClient; DTLS enabled; network blocks UDP",
        "steps": "1. Enable DTLS tunnel mode | 2. Block UDP traffic (simulate DTLS handshake failure) | 3. Verify client falls back to TLS within timeout | 4. Verify tunnel establishes via TLS | 5. Unblock UDP | 6. Verify next reconnect uses DTLS again",
        "expected_result": "DTLS failure triggers automatic TLS fallback; tunnel establishes via TLS",
        "failure_indicators": "grep -i \"DTLS.*fail.*no.*fallback\\|tunnel.*permanent.*fail\\|handshake.*timeout\" nsdebuglog.log",
        "risk": "No DTLS fallback = permanent tunnel failure for users behind UDP-blocking firewalls (ENG-503501)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-07-02", "name": "Proxy Detection After Reboot",
        "feature": "Tunnel Management",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-593814, ENG-463329",
        "preconditions": "Windows device; corporate proxy configured; device rebooted",
        "steps": "1. Configure corporate proxy | 2. Verify tunnel connects through proxy | 3. Reboot device | 4. After reboot, verify proxy is detected before tunnel attempt | 5. Verify addonHost populated before detection (ENG-593814) | 6. After upgrade, verify bootstrap proxy list used until fresh detection (ENG-463329)",
        "expected_result": "Proxy detected correctly after reboot; tunnel connects through proxy",
        "failure_indicators": "grep -i \"proxy.*detect.*fail\\|addonHost.*empty\\|direct.*connect.*fail\" nsdebuglog.log",
        "risk": "Tunnel fails after reboot because proxy not detected (ENG-593814)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-07-03", "name": "Tunnel Reconnect After Network Switch",
        "feature": "Tunnel Management",
        "platform": "Cross-Platform",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-393015, ENG-592681",
        "preconditions": "Device with active tunnel; WiFi and Ethernet available",
        "steps": "1. Verify tunnel connected via WiFi | 2. Switch to Ethernet | 3. Verify tunnel reconnects within 30s | 4. Switch back to WiFi | 5. Rapidly switch 5 times in succession | 6. Verify no crash (ENG-393015) and tunnel recovers after each switch",
        "expected_result": "Tunnel reconnects after every network change; no crash; recovery within 30s",
        "failure_indicators": "grep -i \"crash\\|reconnect.*fail\\|network.*switch.*error\" nsdebuglog.log; crash dump in ProgramData/Netskope",
        "risk": "NPA crash on network switch (ENG-393015); Android tunnel drops repeatedly (ENG-592681)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-07-04", "name": "Heartbeat and GSLB Health Check",
        "feature": "Tunnel Management",
        "platform": "Cross-Platform",
        "severity": "S2", "auto_priority": "P1", "gap_type": "Day-1",
        "related_bugs": "ENG-533981, ENG-398819",
        "preconditions": "Device with active tunnel; multiple POPs available",
        "steps": "1. Verify heartbeat messages sent at expected interval | 2. Simulate heartbeat error (0xa9/0xac response) | 3. Verify POP switch triggered on health check failure | 4. Verify GSLB selects correct POP (not distant one, ENG-398819) | 5. Verify no DNS health check flapping (ENG-533981) | 6. Verify tunnel stable after POP switch",
        "expected_result": "Heartbeat detects unhealthy POP; GSLB switches to nearest healthy POP",
        "failure_indicators": "grep -i \"heartbeat.*fail\\|POP.*switch\\|GSLB.*wrong\\|flap\" nsdebuglog.log",
        "risk": "Flapping health checks cause tunnel instability (ENG-533981); wrong POP selected (ENG-398819)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-07-05", "name": "DEM Thread Crash Does Not Kill Tunnel",
        "feature": "Tunnel Management",
        "platform": "Cross-Platform",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-593503",
        "preconditions": "Device with DEM enabled; tunnel active",
        "steps": "1. Verify tunnel and DEM both active | 2. Trigger DEM thread crash (stack overrun scenario) | 3. Verify tunnel remains connected despite DEM crash | 4. Verify DEM recovers or is disabled gracefully | 5. Verify no other modules affected | 6. Verify traffic continues flowing through tunnel",
        "expected_result": "DEM thread failure is isolated; tunnel continues operating",
        "failure_indicators": "grep -i \"DEM.*crash.*tunnel\\|stack.*overrun\\|service.*crash\" nsdebuglog.log",
        "risk": "DEM crash takes down entire tunnel (ENG-593503)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-07-06", "name": "Android Tunnel Stability — 90 Second Disconnect",
        "feature": "Tunnel Management",
        "platform": "Android",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-429034, ENG-592681",
        "preconditions": "Android device with NSClient; tunnel connected; WiFi",
        "steps": "1. Verify tunnel connected | 2. Wait 90 seconds (1m30s) | 3. Verify tunnel does NOT disconnect (ENG-429034) | 4. Switch to mobile data | 5. Verify tunnel reconnects | 6. Monitor for 10 minutes — verify no repeated drops (ENG-592681)",
        "expected_result": "Tunnel stays connected beyond 90s; reconnects cleanly after network change",
        "failure_indicators": "grep -i \"disconnect.*90\\|1.*min.*30\\|tunnel.*drop.*repeat\" nsdebuglog.log",
        "risk": "Android tunnel drops every 90 seconds rendering client useless (ENG-429034)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-07-07", "name": "NPA Tunnel Recovery After Disconnect",
        "feature": "Tunnel Management",
        "platform": "Cross-Platform",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-441957",
        "preconditions": "Device with NPA enabled; NPA tunnel connected; private apps accessible",
        "steps": "1. Verify NPA tunnel connected and private apps accessible | 2. Force NPA tunnel disconnect (network blip) | 3. Verify NPA tunnel auto-reconnects | 4. Verify private apps become accessible again | 5. Repeat disconnect 3 times | 6. Verify no permanent NPA failure state",
        "expected_result": "NPA tunnel always recovers after disconnect; private apps remain accessible",
        "failure_indicators": "grep -i \"NPA.*not.*recover\\|NPA.*disconnect.*permanent\\|private.*app.*fail\" nsdebuglog.log",
        "risk": "NPA does not recover after disconnect — permanent private app access loss (ENG-441957)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-07-08", "name": "DNS Flush Deadlock During Reconnect",
        "feature": "Tunnel Management",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P1", "gap_type": "Day-1",
        "related_bugs": "ENG-751720",
        "preconditions": "Windows device; tunnel reconnecting after disconnect",
        "steps": "1. Disconnect tunnel (simulate network loss) | 2. During reconnect, observe DNS flush operation | 3. Verify DNS flush does not deadlock (ENG-751720) | 4. Verify tunnel reconnects within 60s | 5. Verify DNS resolution works after reconnect | 6. Repeat disconnect/reconnect 5 times",
        "expected_result": "DNS flush completes without deadlock; tunnel reconnects; DNS works",
        "failure_indicators": "grep -i \"DNS.*flush.*stuck\\|deadlock\\|DNS.*timeout\" nsdebuglog.log",
        "risk": "DNS flush deadlock causes permanent connectivity loss (ENG-751720)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-07-09", "name": "Tunnel Connect Through Authenticated Proxy",
        "feature": "Tunnel Management",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P1", "gap_type": "Day-1",
        "related_bugs": "ENG-593814, ENG-463329",
        "preconditions": "Windows device behind authenticated proxy (NTLM/Basic/Kerberos)",
        "steps": "1. Configure authenticated proxy | 2. Verify tunnel connects through proxy with credentials | 3. Change proxy credentials | 4. Verify re-authentication on next reconnect | 5. Remove proxy — verify direct connection | 6. Restore proxy — verify proxy detection resumes",
        "expected_result": "Tunnel connects through authenticated proxy; handles credential changes",
        "failure_indicators": "grep -i \"proxy.*auth.*fail\\|407\\|NTLM.*error\" nsdebuglog.log",
        "risk": "Users behind corporate proxy cannot establish tunnel",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-07-10", "name": "Tunnel Stability Under Sustained Load",
        "feature": "Tunnel Management",
        "platform": "Cross-Platform",
        "severity": "S2", "auto_priority": "P2", "gap_type": "Test Gap",
        "related_bugs": "",
        "preconditions": "Device with tunnel connected; high traffic volume",
        "steps": "1. Establish tunnel connection | 2. Generate sustained traffic (100 Mbps for 30 minutes) | 3. Monitor tunnel stability (no disconnects) | 4. Monitor memory usage (no leak) | 5. Verify heartbeat still functioning under load | 6. Verify latency remains acceptable (< 50ms overhead)",
        "expected_result": "Tunnel stable under load; no memory leak; heartbeat normal; acceptable latency",
        "failure_indicators": "grep -i \"disconnect\\|timeout\\|memory.*grow\\|heartbeat.*miss\" nsdebuglog.log",
        "risk": "Tunnel unstable under real-world traffic loads",
        "automation": "❌ Not covered",
    },
]

# Ch11: FailClose — 28 bugs
CH11_TCS = [
    {
        "id": "TC-11-01", "name": "FailClose Activation After Reboot",
        "feature": "FailClose",
        "platform": "Windows",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-895081",
        "preconditions": "Windows device; FailClose enabled; tunnel connected",
        "steps": "1. Verify FailClose enabled and tunnel connected | 2. Reboot device | 3. After boot, verify FailClose activates before tunnel re-establishes | 4. Verify traffic blocked during tunnel reconnect | 5. Once tunnel reconnects, verify FailClose deactivates | 6. Verify no residual blocking after tunnel up",
        "expected_result": "FailClose correctly blocks traffic post-reboot until tunnel reconnects; then deactivates",
        "failure_indicators": "grep -i \"FailClose.*not.*blocking\\|reboot.*bypass\\|traffic.*leak\" nsdebuglog.log",
        "risk": "Traffic not blocked after reboot — security gap window (ENG-895081)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-11-02", "name": "FailClose False Activation on Config Update",
        "feature": "FailClose",
        "platform": "Windows",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-422599",
        "preconditions": "Windows device; FailClose enabled; tunnel connected; admin making config changes",
        "steps": "1. Verify tunnel connected and FailClose not active | 2. Admin changes policy (config update) | 3. Verify FailClose does NOT activate during config download | 4. Verify tunnel stays connected during config apply | 5. Verify traffic not interrupted | 6. Repeat with multiple rapid config changes",
        "expected_result": "Config update does not trigger false FailClose; traffic uninterrupted",
        "failure_indicators": "grep -i \"FailClose.*active.*config\\|config.*update.*block\" nsdebuglog.log",
        "risk": "Every admin config change triggers FailClose, blocking all users (ENG-422599)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-11-03", "name": "Captive Portal Detection and Bypass",
        "feature": "FailClose",
        "platform": "Cross-Platform",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Day-1",
        "related_bugs": "ENG-548975, ENG-482990, ENG-750658, ENG-795413",
        "preconditions": "Device with FailClose enabled; connected to network requiring captive portal",
        "steps": "1. Connect to captive portal network (hotel/airport WiFi) | 2. Verify FailClose detects captive portal | 3. Verify grace period allows portal authentication | 4. Test meta refresh redirect (ENG-482990) | 5. Test single-quote URL parsing (ENG-750658) | 6. Test multiple meta tags (ENG-795413) | 7. Complete portal auth — verify tunnel connects and FailClose deactivates",
        "expected_result": "Captive portal detected; user can authenticate; FailClose resumes after auth",
        "failure_indicators": "grep -i \"captive.*portal.*fail\\|meta.*refresh\\|grace.*period.*expire\" nsdebuglog.log",
        "risk": "Users blocked from internet at hotels/airports due to captive portal not detected",
        "automation": "⚠️ Partial — fail_close/test_p0.py covers basic FC",
    },
    {
        "id": "TC-11-04", "name": "FailClose with On-Prem Detection (Steering=NONE)",
        "feature": "FailClose",
        "platform": "Windows",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-384041",
        "preconditions": "Windows device; FailClose enabled; Dynamic Steering with NONE on-prem profile",
        "steps": "1. Configure on-prem steering = NONE (no tunnel needed on corporate network) | 2. Connect to corporate network (on-prem detected) | 3. Verify FailClose does NOT activate (NONE mode = backed off) | 4. Disconnect from corporate (go off-prem) | 5. Verify tunnel starts and FailClose ready | 6. If tunnel fails off-prem, verify FailClose activates correctly",
        "expected_result": "NONE on-prem does not trigger FailClose; off-prem correctly enters FC mode",
        "failure_indicators": "grep -i \"NONE.*FailClose.*active\\|on-prem.*block\" nsdebuglog.log",
        "risk": "On-prem users with NONE mode get traffic blocked (ENG-384041)",
        "automation": "⚠️ Partial — nplan_4571 covers FC + DSE",
    },
    {
        "id": "TC-11-05", "name": "FailClose Exception Domain List",
        "feature": "FailClose",
        "platform": "Cross-Platform",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Test Gap",
        "related_bugs": "ENG-482990, ENG-548975",
        "preconditions": "Device with FailClose active (tunnel disconnected); FC exception domains configured",
        "steps": "1. Trigger FailClose (disconnect tunnel) | 2. Access FC exception domain (e.g., *.enrollment.netskope.com) — verify bypassed | 3. Access non-exception domain (e.g., office.com) — verify blocked | 4. Access private IP — verify bypassed (unless failcloseBlockPrivateTraffic set) | 5. Access captive portal detection URL — verify bypassed | 6. Verify exception list from fail_close.domains in config",
        "expected_result": "Only FC exception domains, private IPs, and captive portal bypass during FailClose",
        "failure_indicators": "grep -i \"exception.*not.*bypass\\|blocked.*should.*bypass\\|bypass.*should.*block\" nsdebuglog.log",
        "risk": "FC exceptions not working — users can't enroll or authenticate while FailClosed",
        "automation": "⚠️ Partial — nplan_4571/test_nplan_4571_failclose.py",
    },
    {
        "id": "TC-11-06", "name": "VDI Master Image FailClose Config Mismatch",
        "feature": "FailClose",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P2", "gap_type": "Corner Case",
        "related_bugs": "ENG-752117",
        "preconditions": "Citrix VDI; master image has FC enabled; tenant config has FC disabled",
        "steps": "1. Golden image has local FailClose config = enabled | 2. Tenant admin disables FailClose in cloud | 3. Clone VM from golden image | 4. Observe race between local config (FC on) and downloaded config (FC off) | 5. Verify downloaded config wins after sync | 6. Verify no traffic blocking during config sync window",
        "expected_result": "Downloaded config overrides local; FC correctly disabled after sync",
        "failure_indicators": "grep -i \"config.*mismatch\\|local.*override\\|VDI.*FailClose\" nsdebuglog.log",
        "risk": "VDI clones stuck with wrong FC state; users blocked despite admin disabling FC (ENG-752117)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-11-07", "name": "Multi-User FailClose Session Isolation",
        "feature": "FailClose",
        "platform": "Windows",
        "severity": "S1", "auto_priority": "P2", "gap_type": "Day-1",
        "related_bugs": "ENG-928461, ENG-591721",
        "preconditions": "Windows Server RDS with 3+ active user sessions; FailClose enabled",
        "steps": "1. User A, B, C all connected with tunnels | 2. User A's tunnel disconnects (triggers FC evaluation) | 3. Verify User A's traffic blocked | 4. Verify User B and C traffic NOT blocked (session isolation) | 5. User A reconnects — verify FC deactivates for A | 6. Verify no deadlock between sessions (ENG-591721)",
        "expected_result": "FailClose isolated per session; one user's disconnect doesn't block others",
        "failure_indicators": "grep -i \"all.*user.*blocked\\|session.*isolation.*fail\\|deadlock\" nsdebuglog.log",
        "risk": "One user's tunnel failure blocks ALL users in RDS environment (ENG-928461)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-11-08", "name": "FailClose Driver Rules Cleanup on Service Stop",
        "feature": "FailClose",
        "platform": "Windows",
        "severity": "S1", "auto_priority": "P1", "gap_type": "Test Gap",
        "related_bugs": "ENG-733657, ENG-895081",
        "preconditions": "Windows device; FailClose currently active (blocking traffic)",
        "steps": "1. Verify FailClose active and traffic blocked | 2. Stop stAgentSvc service | 3. Verify FilterDevice/WFP rules are REMOVED on stop | 4. Verify user can access internet after service stops | 5. Start service again — verify FC re-engages correctly | 6. Kill service (crash) — verify WFP rules still removed",
        "expected_result": "Service stop always clears FC driver rules; no permanent block after service exit",
        "failure_indicators": "User cannot access internet after service stop; WFP rules persist",
        "risk": "Residual WFP rules cause permanent network block even after uninstall (ENG-733657)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-11-09", "name": "FailClose Grace Period Timing",
        "feature": "FailClose",
        "platform": "Cross-Platform",
        "severity": "S2", "auto_priority": "P2", "gap_type": "Day-1",
        "related_bugs": "ENG-548975",
        "preconditions": "Device with FailClose enabled; grace period configured",
        "steps": "1. Disconnect tunnel to trigger FC | 2. Verify grace period timer starts | 3. During grace period, verify traffic still flows | 4. Verify GSLB refresh completes within grace period (ENG-548975) | 5. If tunnel reconnects during grace — verify FC does not activate | 6. If grace expires without tunnel — verify FC activates",
        "expected_result": "Grace period allows tunnel reconnect without blocking; activates only after expiry",
        "failure_indicators": "grep -i \"grace.*period\\|timing\\|premature.*block\" nsdebuglog.log",
        "risk": "Grace period too short — FC activates before GSLB can select new POP (ENG-548975)",
        "automation": "❌ Not covered",
    },
    {
        "id": "TC-11-10", "name": "FailClose with Steering Mode Transition",
        "feature": "FailClose",
        "platform": "Windows",
        "severity": "S2", "auto_priority": "P1", "gap_type": "Regression",
        "related_bugs": "ENG-591725, ENG-422599",
        "preconditions": "Windows device; FailClose enabled; steering mode about to change",
        "steps": "1. Current mode = NONE, tunnel not connected, FC backed off | 2. Admin changes to WEB mode (config update) | 3. Verify tunnel starts connecting | 4. During tunnel connect, verify FC does NOT falsely activate | 5. Once tunnel connected, verify FC ready state | 6. Disconnect tunnel — verify FC correctly activates now",
        "expected_result": "Steering mode transition does not falsely trigger FailClose",
        "failure_indicators": "grep -i \"mode.*change.*FailClose\\|false.*activation\\|transition.*block\" nsdebuglog.log",
        "risk": "Every mode transition blocks traffic; admin config changes cause user outage",
        "automation": "❌ Not covered",
    },
]

if __name__ == "__main__":
    # Just print summary
    print(f"Ch03 Service Lifecycle: {len(CH03_TCS)} TCs")
    print(f"Ch05 Steering Config: {len(CH05_TCS)} TCs")
    print(f"Ch07 Tunnel Management: {len(CH07_TCS)} TCs")
    print(f"Ch11 FailClose: {len(CH11_TCS)} TCs")
    print(f"Total new: {len(CH03_TCS) + len(CH05_TCS) + len(CH07_TCS) + len(CH11_TCS)} TCs")
